#!/usr/bin/env python3
"""Render the scoping-review workflow output JSON into markdown docs."""
import json, html, os, sys

if len(sys.argv) < 2:
    sys.exit("usage: assemble_review.py <workflow-output.json>  "
             "(the scoping-review workflow result; a historical one-off tool)")
SRC = sys.argv[1]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REV = os.path.join(ROOT, "docs", "scoping_review")
DES = os.path.join(ROOT, "docs", "design")
os.makedirs(REV, exist_ok=True)
os.makedirs(DES, exist_ok=True)

d = json.load(open(SRC))
r = d["result"] if "result" in d else d

def u(s):
    return html.unescape(s) if isinstance(s, str) else s

def cell(s):
    s = u(s or "")
    return s.replace("\n", " ").replace("|", "\\|").strip()

def write(path, text):
    with open(path, "w") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))

# --- per-class catalog sections -------------------------------------------
CLASS_ORDER = ["Visual", "Audio", "Language", "Social", "Situation", "Affect"]
by_class = {}
for c in r["catalogs"]:
    by_class.setdefault(u(c["class"]), []).append(c)

def render_catalog(c):
    out = [f"## {u(c['subclass'])}\n", u(c["summary"]) + "\n"]
    out.append("| Tool | Measures | Per-timepoint output | Modality | Granularity | Local | Rating | Rec |")
    out.append("|------|----------|----------------------|----------|-------------|-------|--------|-----|")
    for t in c.get("tools", []):
        out.append("| {} | {} | {} | {} | {} | {} | {} | {} |".format(
            cell(t.get("name")), cell(t.get("what_it_measures")), cell(t.get("output_features")),
            cell(t.get("input_modality")), cell(t.get("temporal_granularity")),
            cell(t.get("local_deployable")), cell(t.get("rating")), cell(t.get("recommendation"))))
    out.append("")
    if c.get("recommended_best_in_class"):
        out.append("**Recommended (best-in-class):** " + "; ".join(u(x) for x in c["recommended_best_in_class"]) + "\n")
    if c.get("likely_redundant"):
        out.append("**Likely redundant:**")
        out += [f"- {u(x)}" for x in c["likely_redundant"]]
        out.append("")
    if c.get("open_questions"):
        out.append("**Open questions:**")
        out += [f"- {u(x)}" for x in c["open_questions"]]
        out.append("")
    # references appendix per tool
    refs = [(u(t.get('name')), u(t.get('references'))) for t in c.get("tools", []) if t.get("references")]
    if refs:
        out.append("<details><summary>References</summary>\n")
        out += [f"- **{n}** — {ref}" for n, ref in refs]
        out.append("\n</details>")
    out.append("")
    return "\n".join(out)

class_files = {}
for i, cls in enumerate(CLASS_ORDER, start=2):
    cats = by_class.get(cls, [])
    if not cats:
        continue
    fname = f"{i:02d}_{cls.lower()}.md"
    body = [f"# {cls} features\n"]
    for c in cats:
        body.append(render_catalog(c))
    write(os.path.join(REV, fname), "\n".join(body))
    class_files[cls] = fname

# --- narrative sections ----------------------------------------------------
write(os.path.join(REV, "00_overview.md"),
      "# Scoping Review — Overview & Executive Summary\n\n" + u(r["executive"]) + "\n")
write(os.path.join(REV, "01_hierarchy.md"),
      "# Semantic Feature Hierarchy\n\n" + u(r["hierarchy"]) + "\n")
write(os.path.join(REV, "08_redundancy.md"),
      "# Redundancy & Parsimony Analysis\n\n" + u(r["redundancy"]) + "\n")
write(os.path.join(REV, "09_recommendations.md"),
      "# Recommendations — Best-in-Class Feature Set\n\n" + u(r["recommendations"]) + "\n")
# NOTE: the schema and deployment agents wrote richer standalone docs directly to
# docs/design/ANNOTATION_FORMAT.md and docs/design/DEPLOYMENT_FEASIBILITY.md.
# Those are authoritative; we deliberately do NOT overwrite them here (a lowercase
# filename here would collide with them on case-insensitive filesystems).

# --- index -----------------------------------------------------------------
idx = ["# Scoping Review — Computational Tools for Second-by-Second Annotation of Movies and Stories\n",
       "Generated by a 21-agent research workflow. Sections:\n",
       "1. [Overview & Executive Summary](00_overview.md)",
       "2. [Semantic Feature Hierarchy](01_hierarchy.md)"]
n = 3
for cls in CLASS_ORDER:
    if cls in class_files:
        idx.append(f"{n}. [{cls} features]({class_files[cls]})"); n += 1
idx += [f"{n}. [Redundancy & Parsimony Analysis](08_redundancy.md)",
        f"{n+1}. [Recommendations — Best-in-Class Feature Set](09_recommendations.md)",
        "",
        "Companion design docs: [annotation output format](../design/ANNOTATION_FORMAT.md), "
        "[deployment feasibility](../design/DEPLOYMENT_FEASIBILITY.md), "
        "[implementation plan](../design/IMPLEMENTATION_PLAN.md).",
        "",
        f"_Catalog covers {sum(len(c.get('tools',[])) for c in r['catalogs'])} tools across "
        f"{len(r['catalogs'])} feature subclasses._"]
write(os.path.join(REV, "README.md"), "\n".join(idx) + "\n")
print("done")
